export default {
  layer_num: 16,
  layers: null,
  rx: null,
  img: null,
  image_data: null,
  x_offset: -16 * 8,
  y_offset: -16 * 8,
  zoom: 1,
  km: {},
  mouse_down: null,
  offset_cache: null,
  show_controls: true,
  show_info: true,
  touch_mode: false,
}
