export default {
  layer_num: 16,
  layers: null,
  rx: null,
  img: null,
  image_data: null,
  x_offset: -14 * 8,
  y_offset: 4 * 8,
  // x_offset: 0,
  // y_offset: 0,
  zoom: 1,
  km: {},
  mouse_down: null,
  offset_cache: null,
  show_controls: true,
  show_info: true,
  touch_mode: false,
}
